# Generated by Django 3.1.1 on 2020-09-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='nome',
            new_name='titulo',
        ),
    ]
