# Generated by Django 3.1.1 on 2020-09-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20200911_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data_zeramento',
            field=models.DateField(),
        ),
    ]
