# Generated by Django 3.1.1 on 2020-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0007_auto_20200912_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='plataforma',
            field=models.CharField(choices=[('--', '--'), ('PC', 'PC'), ('Xbox One', 'Xbox One'), ('Play Station 4', 'Play Station 4'), ('Nintendo Switch', 'Nintendo Switch'), ('Outra', 'Outra')], default='--', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='zerado',
            field=models.CharField(choices=[('--', '--'), ('Sim', 'Sim'), ('Não', 'Não'), ('Não se aplica', 'Não se aplica')], default='--', max_length=20),
        ),
    ]
