# Generated by Django 3.1.1 on 2020-09-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0008_auto_20200912_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
